{% set version = "asp_3.4.0_alpha" %} # dependencies synched up to this version of ISIS
package:
    name: multiview
    version: {{ version }}

source:
  git_url: git@github.com:NeoGeographyToolkit/MultiView.git
# Note: No tag here; will compile the latest

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - git
        
    host:
        - ilmbase 2.5.5
        - openexr 2.5.5
        - boost 1.78.0
        - boost-cpp 1.78.0
        - curl 8.4.0
        - flann 1.9.1
        - gflags 2.2.2
        - glog 0.7.1
        - gmp 6.3.0
        - giflib 5.2.2
        - libopencv 4.9.0
        - libpng 1.6.47
        - libprotobuf 4.24.4
        - libtiff 4.6.0
        - llvm-openmp 20.1.2
        - mpfr 4.2.1
        - numpy 1.26.4
        - opencv 4.9.0
        - openjpeg 2.5.2
        - protobuf 4.24.4
        - python 3.10.15
        - qhull 2020.2
        - pcl 1.13.1
        - qt-main 5.15.8
        - rapidjson 1.1.0
        - rocksdb 8.5.3
        - suitesparse 5.10.1
        - superlu 5.2.2
        - eigen 3.4.0
        - mesalib
        - tbb 2022.1.0
        - tbb-devel 2022.1.0
        - ceres-solver 2.2.0
        - mysql-libs
        - mysql-common
        - mesa-libgl-cos6-x86_64 # [linux]
        - xorg-libxmu # [linux] 
        - xorg-libice # [linux]
        - xorg-libsm # [linux]

    run:
        - ilmbase 2.5.5
        - openexr 2.5.5
        - boost 1.78.0
        - boost-cpp 1.78.0
        - curl 8.4.0
        - flann 1.9.1
        - gflags 2.2.2
        - glog 0.7.1
        - gmp 6.3.0
        - giflib 5.2.2
        - libopencv 4.9.0
        - libpng 1.6.47
        - libprotobuf 4.24.4
        - libtiff 4.6.0
        - llvm-openmp 20.1.2
        - mpfr 4.2.1
        - numpy 1.26.4
        - opencv 4.9.0
        - openjpeg 2.5.2
        - protobuf 4.24.4
        - python 3.10.15
        - qhull 2020.2
        - pcl 1.13.1
        - qt-main 5.15.8
        - rapidjson 1.1.0
        - rocksdb 8.5.3
        - suitesparse 5.10.1
        - superlu 5.2.2
        - eigen 3.4.0
        - mesalib
        - tbb 2022.1.0
        - tbb-devel 2022.1.0
        - ceres-solver 2.2.0
        - mysql-libs
        - mysql-common
        - mesa-libgl-cos6-x86_64 # [linux]
        - xorg-libxmu # [linux] 
        - xorg-libice # [linux]
        - xorg-libsm # [linux]

test:

about:
    home: https://github.com/NeoGeographyToolkit/MultiView
    license: Apache II
    summary: A collection of tools for calibration of a rig of N image and/or depth+image cameras, fusion of point clouds into a mesh, and seamless texturing of meshes 

extra:
  recipe-maintainers:
          - oleg.alexandrov@gmail.com
